# Convert input data to desired format 

In [1]:
import pickle
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
regiondata_url = "./gmql_data/Datasets/gs_breast_finale.pickle"
regiondata = pickle.load(open(regiondata_url, "rb"))

In [3]:
regiondata

normalized_count            \
gene_symbol                                               A1BG  A1BG-AS1   
manually_curated__tissue_status sample                                     
tumoral                         files\S_00000         216.9506  214.4831   
                                files\S_00001         128.9070  183.4258   
                                files\S_00002         161.2486  100.7430   
                                files\S_00003         127.1454  127.8283   
                                files\S_00004          74.5163  141.5685   
                                files\S_00005         341.4830  155.5912   
                                files\S_00006         180.3284  109.5081   
                                files\S_00007         101.3246  120.9196   
                                files\S_00008         117.7966   73.5508   
                                files\S_00009         192.7825  251.1441   
                                files\S_00010          49.1992   75.0039   
                                files\S_00011         222.6672  175.3532   
                                files\S_00012         220.4913  269.9923   
                                files\S_00013         100.5562  130.1150   
                                files\S_00014         616.6585  180.1730   
normal                          files\S_00015          80.8742  128.5481   
tumoral                         files\S_00016         142.8677   88.0352   
                                files\S_00017         111.3007  126.4392   
                                files\S_00018         498.7862  250.2883   
                                files\S_00019          78.1975  129.2912   
                                files\S_00020          77.9087  106.2513   
normal                          files\S_00021          19.0722   33.5206   
tumoral                         files\S_00022         106.6447  131.5072   
                                files\S_00023         104.6192  134.1636   
normal                          files\S_00024          49.2346  105.1292   
tumoral                         files\S_00025         408.9985  317.6138   
                                files\S_00026          28.4304   67.3590   
                                files\S_00027         134.9986  156.4523   
                                files\S_00028         189.4169  139.7979   
                                files\S_00029         104.2612  112.4857   
...                                                        ...       ...   
                                files\S_01188         101.1541  134.2876   
                                files\S_01189         198.8155  134.2182   
                                files\S_01190          36.3125   63.4694   
normal                          files\S_01191         103.0203  149.4418   
tumoral                         files\S_01192          67.4286  149.3827   
                                files\S_01193         205.0052  230.4302   
                                files\S_01194         231.0080  131.8916   
                                files\S_01195          74.6616  102.5811   
                                files\S_01196         462.6501  347.1687   
                                files\S_01197         130.9902  153.8508   
                                files\S_01198          96.4748  135.7230   
                                files\S_01199         139.5113  180.9456   
                                files\S_01200         124.5250   82.1632   
                                files\S_01201          35.0230   40.6498   
                                files\S_01202         137.2796  191.7680   
                                files\S_01203          85.1178  151.8677   
                                files\S_01204         112.2456  240.4453   
                                files\S_01205         199.4404  123.4023   
                                files\S_01206         151.3668  225.8155   
                  

Get labels from the index

In [4]:
lbls = regiondata.index.get_level_values('manually_curated__tissue_status')
len(lbls)

1218

In [5]:
lbls= ["1" if x=="tumoral" else "0" for x in lbls]
for i in range(len(lbls)):
    lbls[i] = int(lbls[i])

Dump the unnecessery columns

In [6]:
regiondata = regiondata.normalized_count
regiondata.index = regiondata.index.get_level_values(-1)
regiondata.head()

gene_symbol        A1BG  A1BG-AS1    A1CF         A2M  A2M-AS1    A2ML1  \
sample                                                                    
files\S_00000  216.9506  214.4831  0.0000   4648.3610  28.5221   1.0390   
files\S_00001  128.9070  183.4258  0.4078  14028.9356  15.5179   3.6705   
files\S_00002  161.2486  100.7430  0.0000  17754.2889  23.3321   0.0000   
files\S_00003  127.1454  127.8283  0.0000   9604.5625  22.4744   7.2420   
files\S_00004   74.5163  141.5685  0.0000  11410.8522  25.1297  25.1132   

gene_symbol      A4GALT   A4GNT      AAAS       AACS    ...        ZWILCH  \
sample                                                  ...                 
files\S_00000  104.4156  0.0000  825.9740   741.5584    ...      197.4026   
files\S_00001  183.9315  1.6313  676.9984   855.6281    ...      569.2659   
files\S_00002  807.9038  0.0000  668.4097   919.9974    ...      188.4209   
files\S_00003  209.3284  0.0000  919.3896   781.1018    ...      609.5043   
files\S_00004  274.1869  4.5286  669.4113  1374.6398    ...     1098.3573   

gene_symbol       ZWINT      ZXDA       ZXDB       ZXDC   ZYG11A     ZYG11B  \
sample                                                                        
files\S_00000  327.7922   64.6753  1089.6104  1021.2987  15.3247   740.0000   
files\S_00001  679.0375  147.6346   883.3605  1214.9266  74.6330   855.6281   
files\S_00002  567.5255   12.8700   168.5555   520.6122  43.5919   473.2839   
files\S_00003  722.1312   43.7969   359.3413   991.1199  67.5920   403.8279   
files\S_00004  291.0663  104.1581   792.9189  1813.0918  63.8123  1041.1692   

gene_symbol          ZYX      ZZEF1      ZZZ3  
sample                                         
files\S_00000  1280.5195  1615.3247  842.5974  
files\S_00001  3809.1354  1853.5889  716.9657  
files\S_00002  4341.3414   807.9038  435.0890  
files\S_00003  6222.2605  1072.8511  442.7968  
files\S_00004  4456.1548  1162.6184  901.1939  

[5 rows x 20207 columns]

In [7]:
regiondata = regiondata.fillna(regiondata.mean())
regiondata = regiondata.dropna(axis=1, how='all')

In [8]:
regiondata

gene_symbol        A1BG  A1BG-AS1    A1CF         A2M   A2M-AS1      A2ML1  \
sample                                                                       
files\S_00000  216.9506  214.4831  0.0000   4648.3610   28.5221     1.0390   
files\S_00001  128.9070  183.4258  0.4078  14028.9356   15.5179     3.6705   
files\S_00002  161.2486  100.7430  0.0000  17754.2889   23.3321     0.0000   
files\S_00003  127.1454  127.8283  0.0000   9604.5625   22.4744     7.2420   
files\S_00004   74.5163  141.5685  0.0000  11410.8522   25.1297    25.1132   
files\S_00005  341.4830  155.5912  0.0000   2512.5972   13.2545     0.8016   
files\S_00006  180.3284  109.5081  0.0000  28739.2847   55.5089  3515.2196   
files\S_00007  101.3246  120.9196  0.0000   8586.3106   24.0443     0.5210   
files\S_00008  117.7966   73.5508  0.0000   9871.0847   11.9661     5.0847   
files\S_00009  192.7825  251.1441  0.0000   9226.3842   15.1412     0.4708   
files\S_00010   49.1992   75.0039  0.0000  31626.9490   28.4176     3.1535   
files\S_00011  222.6672  175.3532  0.0000  10548.8553   36.7133     1.8889   
files\S_00012  220.4913  269.9923  0.0000  28120.3800   36.4290  2312.7621   
files\S_00013  100.5562  130.1150  0.0000   8568.4645   18.1390     0.8364   
files\S_00014  616.6585  180.1730  0.0000   7832.7832   16.7374     0.5055   
files\S_00015   80.8742  128.5481  0.0000  25382.8067   68.6247    48.0573   
files\S_00016  142.8677   88.0352  0.0000   8592.7825   26.1840    27.2572   
files\S_00017  111.3007  126.4392  0.0000  29446.7761   39.4517    27.8134   
files\S_00018  498.7862  250.2883  0.0000   6228.5266   19.4551     6.4834   
files\S_00019   78.1975  129.2912  0.0000  17460.6102   49.9119     2.2358   
files\S_00020   77.9087  106.2513  0.0000   9805.9392   13.4124     0.3426   
files\S_00021   19.0722   33.5206  0.0000  41867.0567   72.6340     9.7938   
files\S_00022  106.6447  131.5072  0.0000   6882.3774   29.1059    48.4450   
files\S_00023  104.6192  134.1636  0.0000   5761.7285   27.3077     0.6274   
files\S_00024   49.2346  105.1292  0.0000  33165.7199   88.5257   105.5870   
files\S_00025  408.9985  317.6138  0.0000   4542.8757   14.1759     3.5381   
files\S_00026   28.4304   67.3590  0.0000  11944.5988   92.6274     2.0429   
files\S_00027  134.9986  156.4523  0.0000   7612.7283   27.9545     6.5434   
files\S_00028  189.4169  139.7979  0.0000  15693.0656   29.1423     5.4418   
files\S_00029  104.2612  112.4857  0.0000  34667.9763   53.2913     3.0546   
...                 ...       ...     ...         ...       ...        ...   
files\S_01188  101.1541  134.2876  0.0000  10181.7311  203.8266     0.0000   
files\S_01189  198.8155  134.2182  0.0000  17129.4172   27.7812     5.0404   
files\S_01190   36.3125   63.4694  0.3519   7903.5749   11.2738    56.6502   
files\S_01191  103.0203  149.4418  0.0000  26732.5545   42.7705    53.9638   
files\S_01192   67.4286  149.3827  0.0000   8850.8124   18.1266     0.0000   
files\S_01193  205.0052  230.4302  0.0000  16641.0205   34.8463     0.0000   
files\S_01194  231.0080  131.8916  0.0000  13194.3494   16.4940     0.0000   
files\S_01195   74.6616  102.5811  0.0000   6185.1982   12.6392     1.6019   
files\S_01196  462.6501  347.1687  0.5176  14337.4379   11.4234     0.0000   
files\S_01197  130.9902  153.8508  0.0000   7032.0082   15.2654     0.2418   
files\S_01198   96.4748  135.7230  0.0000   4946.4883    6.4409     0.3386   
files\S_01199  139.5113  180.9456  0.0000  19459.9708   18.1169     1.5936   
files\S_01200  124.5250   82.1632  0.0000   5481.4429   10.3015     0.0000   
files\S_01201   35.0230   40.6498  0.0000  16361.7097   23.0829   384.7926   
files\S_01202  137.2796  191.7680  0.0000  15847.2183   16.0537  3037.2466   
files\S_01203   85.1178  151.8677  0.0000   8260.9638   22.1878     1.7587   
files\S_01204  112.2456  240.4453  0.2516   8443.0218   18.6715     1.0064   
files\S_01205  199.4404  123.4023  0.0000   6768.3049   29.7486     0.8110   
files\S_01206  151.366

In [9]:
regiondata = (regiondata - regiondata.mean())
regiondata = regiondata / (regiondata.max() - regiondata.min())
regiondata


gene_symbol        A1BG  A1BG-AS1      A1CF       A2M   A2M-AS1     A2ML1  \
sample                                                                      
files\S_00000  0.003705  0.076754 -0.001919 -0.048252 -0.021405 -0.012807   
files\S_00001 -0.007647  0.040938  0.001374 -0.010241 -0.080249 -0.012674   
files\S_00002 -0.003477 -0.054414 -0.001919  0.004855 -0.044890 -0.012859   
files\S_00003 -0.007874 -0.023178 -0.001919 -0.028169 -0.048771 -0.012493   
files\S_00004 -0.014659 -0.007333 -0.001919 -0.020849 -0.036756 -0.011589   
files\S_00005  0.019760  0.008838 -0.001919 -0.056906 -0.090491 -0.012819   
files\S_00006 -0.001017 -0.044305 -0.001919  0.049368  0.100709  0.164906   
files\S_00007 -0.011203 -0.031146 -0.001919 -0.032295 -0.041667 -0.012833   
files\S_00008 -0.009079 -0.085772 -0.001919 -0.027089 -0.096320 -0.012602   
files\S_00009  0.000589  0.119032 -0.001919 -0.029701 -0.081953 -0.012835   
files\S_00010 -0.017923 -0.084096 -0.001919  0.061069 -0.021878 -0.012700   
files\S_00011  0.004442  0.031628 -0.001919 -0.024342  0.015659 -0.012764   
files\S_00012  0.004161  0.140768 -0.001919  0.046860  0.014373  0.104097   
files\S_00013 -0.011302 -0.020541 -0.001919 -0.032367 -0.068388 -0.012817   
files\S_00014  0.055238  0.037187 -0.001919 -0.035348 -0.074731 -0.012834   
files\S_00015 -0.013839 -0.022348 -0.001919  0.035767  0.160057 -0.010429   
files\S_00016 -0.005847 -0.069068 -0.001919 -0.032269 -0.031985 -0.011481   
files\S_00017 -0.009916 -0.024780 -0.001919  0.052235  0.028051 -0.011453   
files\S_00018  0.040041  0.118045 -0.001919 -0.041849 -0.062433 -0.012531   
files\S_00019 -0.014184 -0.021491 -0.001919  0.003665  0.075382 -0.012746   
files\S_00020 -0.014222 -0.048061 -0.001919 -0.027353 -0.089776 -0.012842   
files\S_00021 -0.021807 -0.131936 -0.001919  0.102563  0.178199 -0.012364   
files\S_00022 -0.010517 -0.018936 -0.001919 -0.039199 -0.018764 -0.010409   
files\S_00023 -0.010778 -0.015872 -0.001919 -0.043740 -0.026900 -0.012828   
files\S_00024 -0.017919 -0.049355 -0.001919  0.067304  0.250108 -0.007520   
files\S_00025  0.028465  0.195686 -0.001919 -0.048679 -0.086321 -0.012680   
files\S_00026 -0.020601 -0.092913 -0.001919 -0.018687  0.268668 -0.012756   
files\S_00027 -0.006861  0.009831 -0.001919 -0.036240 -0.023974 -0.012528   
files\S_00028  0.000155 -0.009375 -0.001919 -0.003497 -0.018599 -0.012584   
files\S_00029 -0.010824 -0.040872 -0.001919  0.073392  0.090674 -0.012705   
...                 ...       ...       ...       ...       ...       ...   
files\S_01188 -0.011225 -0.015729 -0.001919 -0.025830  0.771839 -0.012859   
files\S_01189  0.001367 -0.015809 -0.001919  0.002323 -0.024758 -0.012604   
files\S_01190 -0.019585 -0.097398  0.000923 -0.035061 -0.099453 -0.009994   
files\S_01191 -0.010984  0.001747 -0.001919  0.041236  0.043068 -0.010130   
files\S_01192 -0.015573  0.001679 -0.001919 -0.031223 -0.068444 -0.012859   
files\S_01193  0.002165  0.095144 -0.001919  0.000344  0.007211 -0.012859   
files\S_01194  0.005517 -0.018492 -0.001919 -0.013622 -0.075832 -0.012859   
files\S_01195 -0.014640 -0.052294 -0.001919 -0.042024 -0.093275 -0.012778   
files\S_01196  0.035382  0.229769  0.002261 -0.008990 -0.098776 -0.012859   
files\S_01197 -0.007378  0.006831 -0.001919 -0.038593 -0.081391 -0.012847   
files\S_01198 -0.011828 -0.014074 -0.001919 -0.047044 -0.121322 -0.012842   
files\S_01199 -0.006279  0.038078 -0.001919  0.011767 -0.068488 -0.012779   
files\S_01200 -0.008211 -0.075840 -0.001919 -0.044876 -0.103853 -0.012859   
files\S_01201 -0.019751 -0.123714 -0.001919 -0.000788 -0.046017  0.006600   
files\S_01202 -0.006567  0.050558 -0.001919 -0.002873 -0.077824  0.140734   
files\S_01203 -0.013292  0.004544 -0.001919 -0.033613 -0.050068 -0.012770   
files\S_01204 -0.009795  0.106694  0.000113 -0.032875 -0.065979 -0.012808   
files\S_01205  0.001447 -0.028282 -0.001919 -0.039662 -0.015855 -0.012818   
files\S_01206 -0.004751  0.089822 -0.001919 -0.057893 -0.053261 -0.012835

Save base data to pickel file

In [10]:
pickle_file = "./gmql_data/Datasets/breast_data_all_w_labels.p"

try:
    
    f = open(pickle_file, 'wb')
    save = {
    'data': regiondata,
    'labels': lbls,

    }
    pickle.dump(save, f, pickle.HIGHEST_PROTOCOL)
    f.close()
except Exception as e:
    print('Unable to save data to', pickle_file, ':', e)
    raise

    
    
    

# Split the data for train and test

In [11]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedShuffleSplit
import pickle
import numpy as np

In [12]:
pickle_file = "./gmql_data/Datasets/breast_data_all_w_labels.p"
with open(pickle_file, 'rb') as f:
    save = pickle.load(f)
    data = save['data']
    labels = save['labels']
    del save  # hint to help gc free up memory

Set labels to y parameter

In [13]:
x = np.array(data)
y = np.array(labels)
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss.get_n_splits(x, y)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [14]:
for train_index, test_index in sss.split(x, y):
    x_train, x_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]

In [15]:
x_train

array([[  3.64955840e-02,   6.56495584e-02,  -1.91896358e-03, ...,
          2.96413139e-01,  -7.91427000e-02,  -6.74707876e-02],
       [ -1.13294452e-02,  -5.00542809e-02,   6.57146755e-04, ...,
          8.42893195e-02,  -2.82782310e-02,  -3.22926989e-03],
       [  4.54403260e-03,  -4.36160967e-02,  -1.91896358e-03, ...,
         -5.31132268e-03,  -3.00328050e-02,  -2.88051799e-02],
       ..., 
       [  1.48092168e-03,  -2.25529199e-02,  -1.91896358e-03, ...,
          1.65910790e-01,  -1.12622739e-01,  -5.25454215e-02],
       [  1.59026182e-02,  -2.78852836e-02,  -1.91896358e-03, ...,
         -2.48721912e-02,   3.29267534e-02,  -5.37449511e-02],
       [ -9.01547059e-03,   5.23519195e-02,   1.58883409e-04, ...,
         -8.20295370e-02,   2.87572403e-02,   2.17958499e-02]])

In [16]:
x_test

array([[ 0.00952662,  0.07903196, -0.00191896, ...,  0.0244242 ,
         0.00273361,  0.02826876],
       [-0.0086106 , -0.00866633, -0.00191896, ...,  0.3565846 ,
        -0.04618902, -0.02720396],
       [-0.02021831, -0.05124313, -0.00191896, ..., -0.03760679,
        -0.01531181,  0.00319299],
       ..., 
       [-0.00858663,  0.01394642, -0.00191896, ..., -0.10437944,
         0.11332992, -0.01063095],
       [-0.00575942,  0.04758959,  0.00246931, ..., -0.02601109,
        -0.00456936,  0.03479808],
       [ 0.00245662,  0.02299445, -0.00191896, ...,  0.1117065 ,
        -0.10361324, -0.02543221]])

In [17]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1,

In [18]:
y_test

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

Check if the input raito is preserved. Check wit y data since its easier to see

Create validation dataset from training data

In [19]:
x = x_train
z = y_train

sss = StratifiedShuffleSplit(n_splits=3, test_size=0.25, random_state=0)
sss.get_n_splits(x, z)
sss

StratifiedShuffleSplit(n_splits=3, random_state=0, test_size=0.25,
            train_size=None)

In [20]:
for train_index, valid_index in sss.split(x, z):
    x_train, x_valid = x[train_index], x[valid_index]
    z_train, z_valid = z[train_index], z[valid_index]

In [21]:
x_valid

array([[ -5.87087715e-03,   1.67402084e-02,  -1.91896358e-03, ...,
         -3.89933588e-02,  -9.17438951e-02,   2.70760013e-01],
       [ -1.60209429e-02,  -4.60008358e-02,  -1.91896358e-03, ...,
         -1.59804769e-02,   4.05359671e-02,   3.77925855e-02],
       [ -2.00440391e-02,  -7.11853823e-02,  -1.91896358e-03, ...,
          1.62880760e-02,   8.86200330e-02,   4.92304606e-02],
       ..., 
       [ -1.45239724e-02,   1.47595591e-04,  -1.91896358e-03, ...,
          9.79498384e-03,   6.98798585e-02,   5.61715019e-03],
       [ -1.65479750e-02,  -8.87773736e-02,  -1.91896358e-03, ...,
          1.42898974e-01,   1.74705162e-02,  -4.45273991e-02],
       [ -1.70140369e-02,  -5.24773068e-02,  -1.91896358e-03, ...,
          3.88878964e-02,   1.79739371e-02,   3.88155975e-02]])

Save the data for future use

In [ ]:
pickle_file = "./gmql_data/Datasets/breast_data_all_divided_4.pickle"

try:
  f = open(pickle_file, 'wb')
  save = {
    'train_dataset': x_train,
    'train_labels': z_train,
    'test_dataset': x_test,
    'test_labels': y_test,
    'valid_dataset': x_valid,
    'valid_labels': z_valid,
    }
  pickle.dump(save, f, pickle.HIGHEST_PROTOCOL)
  f.close()
except Exception as e:
  print('Unable to save data to', pickle_file, ':', e)
  raise